# **1. Linear Algebra Basics**

# 1.1. Why are we studing linear Algebra?

Think of linear Algebra as basics operations on vectors and matrics.

You've seeen how we can represent groups of numbers in vectors and matrices. This makes them easier to manage. But once we do that, we need to be able to decide what add, subract, multiply etc. means on these "numbers".

So. we learn LINER ALGEBRA so that we can do basics maths on these "numbers".
we are going to see some example down below.

# **1.2. Vectors**

A vector in $(R^{n})$  in an tuple. they can be horizantial and are called *row vector* or vertical in which case they are called *column vertors(the defualt)*.

We created and looked at basic vectors in the numpy intro.

# **1.3. Vector Norm**

The **norm** of a vector is a measure of its length. There are many ways of defining the length of a vector depending on the metric used (i.e., the distance formula chosen). So let's take a look at same distance formulae first.

# **1.3.1. Euclidean Distance**

Euclidean distance is what you are already familiar with. The Euclidean distance between two points (x1, y1) and (x2, y2) is given as

 :
                       $d = √[(x2 – x1)^2 + (y2 – y1)^2]$

Visually, this would look like (see notebook for this).

If we take any vector and take it's x- and y-corridinates as its components, we can redefine the above like so:

This length is then called the L-2 Norm of the vector -- stuff you know as the magnitude. The specific formula is :

:
                         $  |x|2=√(∑vi^2)  $ where ∑i=1

where vi are the elment of the vector v.     


# **1.3.2. Manhetten Distance**

What happens if we don't square the value? It doesn't make sense in the pythogerean sense of the value but sometimes, it is quite useful.

Let's first see what the manhattan distance between two points.

The Manhatten distance between two points (x1,y1) and (x2, y2) is given as:
                            
                            (x2 - x1) + (y2 - y1)

So, basically just adding up the components. Visually, this tooks like:(see notbook)

And the formula is simple too: 
$ ||v||1 = ∑|vi| $  where ∑i=1

# **1.4. Numpy Vectors Revisited**

In [5]:
import numpy as np
from numpy.linalg import norm

In [6]:
vector_row = np.array([[1, -5, 3, 2, 4]])
print(vector_row)
new_vector = vector_row.T
print(new_vector)

norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)

print("L_1 is: %.1f"%norm_1)
print("L_1 is: %.1f"%norm_2)

[[ 1 -5  3  2  4]]
[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L_1 is: 15.0
L_1 is: 7.4


# **1.4.1. Vector Operations**

You would be fimiliar with vector operations. Let's see some examples in code here.

In [7]:
u = np.array([[0, 3, 2]])
v = np.array([[4, 1, 1]])
w = np.array([[0, -2, 0]])

x = 3*u - 2*v + 4*w

print(x)

[[-8 -1  4]]


In [8]:
print(u)
print(v)
print(v.T)

u.dot(v)        # ..... Read the error!

[[0 3 2]]
[[4 1 1]]
[[4]
 [1]
 [1]]


ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [9]:
print(u.shape)
print(v.shape)

(1, 3)
(1, 3)


In [10]:
u = np.array([[0, 3, 2]])
v = np.array([4, 1, 1])             # notice the change here! it's rank one tensor

x = u * v

print(x)

[[0 3 2]]


In [11]:
print(u)
print(v)
print(v.T)      # Does nothing ..

u.dot(v)       # this work here ! due to rank 1 tensor 

[[0 3 2]]
[4 1 1]
[4 1 1]


array([5])

In [12]:
print(u.shape)
print(v.shape)

(1, 3)
(3,)


# **1.5. Matrices** 

Let's see the basics of matrics one more time. Let's also see the relvant terminology side by side.


# *1.5.1. Matrix Multiplication*

In [13]:
P = np.array([[1, 7], [2, 3], [5, 0]])
Q = np.array([[2, 6, 3, 1], [1, 2, 3 , 4]])
print(P)
print(Q)
print(np.dot(P, Q))

np.dot(Q, P)        # can't do that

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [14]:
P.shape, Q.shape

((3, 2), (2, 4))

# **1.5.2. Determinants**

In [15]:
from numpy.linalg import det

M = np.array(
            [  [0, 2, 1, 3],
               [3, 2, 8, 1],
               [1, 0, 0, 3],
               [0, 3, 2, 1],  ]
            )

print('M:\n', M)

print('Determinat: %1.f' % det(M))

I = np.eye(4)   # eye-identity matrix

print('I:\n', I)
print('M=I:\n', np.dot(M, I))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinat: -38
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M=I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


# **1.5.3. Inverse, Singular, Ill-conditioned**

When you multiply something by a matrix and you want to get back, you multiply the result with the inverse of the original matrix. This is similar to multiplying by the reciprocal to reverse the effect of a multiplication.

In [16]:
from numpy.linalg import inv

print('Inv M:\n', inv(M))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]


In [17]:
P = np.array([[0, 1, 0],
              [0, 0, 0],
              [1, 0, 1],])     # Phas no inverse since it is singular.

print('det(P):', det(P))

inv(P)

det(P): 0.0


LinAlgError: Singular matrix

So, multiplying by a singular matrix is sort of like multiplying by 0. It's not reversible.

Ill-conditioned matrices are not singular but their determinant is very close to 0. This makes them problematic just like multiplication by very small numbers can lead to overflow, underflow etc.

# **1.5.4. Rank, Full Rank, Condition Number, Augmented Matrix**

Rank, rank(A), is the number of linerly independent columns or rows of A.

Full rank if rank(A) = min(m,n) for an m X n matrix.

Condition Number: How close is a matrix to being ill-conditoned. Higher is closer to being singular.

Augmented matrix:[A|y] where A is a matrix and y is a vector. y is called new if it cannot be expressed as a combination of columns of A. In this case, rank([A|y]) = rank(A) + 1 (because we just added a new independent column!)

In [18]:
from numpy.linalg import cond, matrix_rank

A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1],])

print('Condition number:\n', cond(A))

print('Rank:\n', matrix_rank(A))

y = np.array([[1, 2, 1]]).T     # need a column vector. Easier to create it using transpose

A_y = np.concatenate((A, y), axis= 1)       # Notice the axis
print('Augmented matrix:\n', A_y)

Condition number:
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


# **2.Solving LU factorization**

# 2.1. LU Decomposition

In [2]:
import numpy as np
from numpy.linalg import inv

import scipy
from scipy.linalg import lu

In [3]:
help(lu)

Help on function lu in module scipy.linalg._decomp_lu:

lu(a, permute_l=False, overwrite_a=False, check_finite=True, p_indices=False)
    Compute LU decomposition of a matrix with partial pivoting.
    
    The decomposition satisfies::
    
        A = P @ L @ U
    
    where ``P`` is a permutation matrix, ``L`` lower triangular with unit
    diagonal elements, and ``U`` upper triangular. If `permute_l` is set to
    ``True`` then ``L`` is returned already permuted and hence satisfying
    ``A = L @ U``.
    
    Parameters
    ----------
    a : (M, N) array_like
        Array to decompose
    permute_l : bool, optional
        Perform the multiplication P*L (Default: do not permute)
    overwrite_a : bool, optional
        Whether to overwrite data in a (may improve performance)
    check_finite : bool, optional
        Whether to check that the input matrix contains only finite numbers.
        Disabling may give a performance gain, but may result in problems
        (crashes, non

In [4]:
A = np.array([
            [  1,   1,  1,   1],
            [  2,   3,  1,   5],
            [ -1,   1, -5,   3],
            [  3,   1,  7,  -2],
        ],  dtype = float )

In [5]:
P,  L,  U = lu(A)

print("A:")
print(A)

print("P:")             # This is a "Permutation"
print(P)                # This tell which row will with which row

print("L:")
print(L)

print("U:")
print(U)

A:
[[ 1.  1.  1.  1.]
 [ 2.  3.  1.  5.]
 [-1.  1. -5.  3.]
 [ 3.  1.  7. -2.]]
P:
[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
L:
[[ 1.          0.          0.          0.        ]
 [ 0.66666667  1.          0.          0.        ]
 [-0.33333333  0.57142857  1.          0.        ]
 [ 0.33333333  0.28571429  0.5         1.        ]]
U:
[[ 3.          1.          7.         -2.        ]
 [ 0.          2.33333333 -3.66666667  6.33333333]
 [ 0.          0.         -0.57142857 -1.28571429]
 [ 0.          0.          0.          0.5       ]]


.dot()    it is a matrix to matrix multiplication

In [6]:
L = P.dot(L)        # Do it just once because it help you to do row exchange to get original matrix back

In [7]:
L.dot(U)        # Produces the same result again "A matrix"

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  3.,  1.,  5.],
       [-1.,  1., -5.,  3.],
       [ 3.,  1.,  7., -2.]])

In [8]:
print(A)

[[ 1.  1.  1.  1.]
 [ 2.  3.  1.  5.]
 [-1.  1. -5.  3.]
 [ 3.  1.  7. -2.]]


In [9]:
L.dot(U) ==  A          # !!! Why?
# as you see they are equal but why some value that are returning false !

        # the reason behind is that in float value there are always some  precision loss so it is recommenended not but it 100 equal as 
        # above do always an approximatly equal or take some uncearity to avoid error

array([[ True, False, False, False],
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [10]:
np.allclose(L.dot(U), A)        # Why?
# Because, it check up to a certian precision not on Absolute value

True

In [11]:
y = np.array([10, 31, -2, 18])          # Is something wrong here?
print(y)

[10 31 -2 18]


**Lm = y**

Let's move L to the other side of the Equation

$L^{-1}$L m = $L^{-1}$ y

m = $L^{-1}$ y

And cancel out....

m = $L^{-1}$ y

In [12]:
m = inv(L).dot(y)

In [13]:
print(m)

[18.         19.         -6.85714286  2.        ]


In [14]:
x = inv(U).dot(m)

In [15]:
print(x)            # Match this with our on-paper results.

[1. 2. 3. 4.]


In [16]:
yp = A.dot(x)
print(yp)

[10. 31. -2. 18.]


In [17]:
np.allclose(y,  yp)

True

# **Gauss_Seidal Method**

$8x_1 + 3x_2 - 3x_3  = 14$

$-2x_1 - 8x_2 - 5x_3  = 5$

$3x_1 + 5x_2 + 10x_3  = -8$

*Gauss_Seidal Method:* It is a bit different in Math term here it mean simple so do how does 'Gauss_Seidal Method' work for better understanding

In [31]:
# to solve with this specific method it is important to have value in diagonal greater then the other two values knows as "diagonally dominant"
a = [
    [ 8, 3, -3],
    [-2,-8,  5],
    [ 3, 5,  10],
]

# Find diagonal coefficients
diag = np.diag(np.abs(a))
print(diag)

[ 8  8 10]


In [32]:
np.sum(np.abs(a), axis=1)           # add all values of rows in matrix

array([14, 15, 18])

In [33]:
# Find row sum without diagonal

off_diag = np.sum(np.abs(a), axis=1) - diag         # subtract the diagnal from each row
print(off_diag)

[6 7 8]


In [34]:
if np.all(diag > off_diag):
    print('matrix is diagonally dominant')      # will converge (sufficient condition for convergence in iterative methods )
else:
    print('Not diagonially dominant')           # may or may not converge (because diagonal dominance is a sufficient but not necessary condition)

matrix is diagonally dominant


Re-arrange the original:

$8x_1 + 3x_2 - 3x_3  = 14$

$-2x_1 - 8x_2 - 5x_3  = 5$

$3x_1 + 5x_2 + 10x_3  = -8$

as:

*Gauss_Seidal Method:* It is a bit different in Math term here it mean simple so do how does 'Gauss_Seidal Method' work for better understanding

$x_1 = (14 - 3x_2 + 3x_3)/8$

$x_2 = (5 +2x_1 - 5x_3)/(-8) $

$x_3  = (-8 - 3x_1 - 5x_2)/10$

In [42]:
# Let's apply the iterative method starting at 0

x1 = 0
x2 = 0
x3 = 0
epsilon = 0.001     # also try better precision
converge = False

x_old = np.array([x1, x2, x3])

In [43]:
max_iteration = 50

In [44]:
print('Iterative results')
print('K    x1        x2         x3')

for k in range(1, max_iteration):
    
    x1 = (14 - 3*x2 + 3*x3)  / 8
    x2 = (5 + 2*x1 - 5*x3)  / (-8)
    x3 = (-8 - 3*x1 - 5*x2)  / 10
    
    x = np.array([x1, x2, x3])
    
    print("%2d   %.4f   %.4f   %.4f " %  (k ,x1,  x2,  x3))
    
    # check if it is smaller than threhold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    if dx < epsilon:
        converge = True
        print('converged!')
        break
    
    # assign the latest x value to the old value
    x_old = x
    
if not converge:
    print('Not converged, increase the # of iterations')

Iterative results
K    x1        x2         x3
 1   1.7500   -1.0625   -0.7937 
 2   1.8508   -1.5838   -0.5633 
 3   2.1327   -1.5103   -0.6847 
 4   2.0596   -1.5678   -0.6340 
 5   2.1002   -1.5463   -0.6569 
 6   2.0835   -1.5565   -0.6468 
 7   2.0911   -1.5520   -0.6513 
 8   2.0878   -1.5540   -0.6493 
 9   2.0893   -1.5531   -0.6502 
10   2.0886   -1.5535   -0.6498 
converged!


In [45]:
8*x1 + 3*x2 - 3*x3

13.997673687371334

In [46]:
-2*x1 - 8*x2 + 5*x3

5.001948405718945

In [47]:
3*x1 + 5*x2 + 10*x3

-8.0

Let's try one where this does NOT work!!!!!

In [48]:
a = [
    [ 1, 3, -3],
    [-2,-1,  5],
    [ 3, 5,  1],
]

# Find diagonal coefficients
diag = np.diag(np.abs(a))
print(diag)

off_diag = np.sum(np.abs(a), axis=1) - diag        
print(off_diag)

if np.all(diag > off_diag):
    print('matrix is diagonally dominant')     
else:
    print('Not diagonially dominant')           

[1 1 1]
[6 7 8]
Not diagonially dominant


In [52]:
# Let's apply the iterative method starting at 0

x1 = 0
x2 = 0
x3 = 0
epsilon = 0.001     # also try better precision
max_iteration = 10
converge = False

x_old = np.array([x1, x2, x3])

print('Iterative results')
print('K    x1        x2         x3')

for k in range(1, max_iteration):
    
    x1 = (14 - 3*x2 + 3*x3)  / 1
    x2 = (5 + 2*x1 - 5*x3)  / (-1)
    x3 = (-8 - 3*x1 - 5*x2)  / 1
    
    x = np.array([x1, x2, x3])
    
    print("%2d   %.4f   %.4f   %.4f " %  (k ,x1,  x2,  x3))
    
    # check if it is smaller than threhold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    if dx < epsilon:
        converge = True
        print('converged!')
        break
    
    # assign the latest x value to the old value
    x_old = x
    
if not converge:
    print('Not converged, increase the # of iterations')

Iterative results
K    x1        x2         x3
 1   14.0000   -33.0000   115.0000 
 2   458.0000   -346.0000   348.0000 
 3   2096.0000   -2457.0000   5989.0000 
 4   25352.0000   -20764.0000   27756.0000 
 5   145574.0000   -152373.0000   325135.0000 
 6   1432538.0000   -1239406.0000   1899408.0000 
 7   9416456.0000   -9335877.0000   18430009.0000 
 8   83297672.0000   -74445304.0000   122333496.0000 
 9   590336414.0000   -569005353.0000   1074017515.0000 
Not converged, increase the # of iterations
